package sbinfo

// Ext2Sb represents an ext2/3/4 superblock.
type Ext2Sb struct {
	SInodesCount uint32
	SBlocksCount uint32
	SRBlocksCount uint32
	SFreeBlocksCount uint32
	SFreeInodesCount uint32
	SFirstDataBlock uint32
	SLogBlockSize uint32
	SLogClusterSize uint32
	SBlocksPerGroup uint32
	SClustersPerGroup uint32
	SInodesPerGroup uint32
	SMtime uint32
	SWtime uint32
	SMntCount uint16
	SMaxMntCount uint16
	SMagic uint16
	SState uint16
	SErrors uint16
	SMinorRevLevel uint16
	SLastcheck uint32
	SCheckinterval uint32
	SCreatorOs uint32
	SRevLevel uint32
	SDefResUID uint16
	SDefResGID uint16
	SFirstIno uint32
	SInodeSize uint16
	SBlockGroupNr uint16
	SFeatureCompat uint32
	SFeatureIncompat uint32
	SFeatureROCompat uint32
	SUUID [16]byte
	SVolumeName [16]byte
	SLastMounted [64]byte
	SAlgorithmUsageBitmap uint32
	SPreallocBlocks uint8
	SPreallocDirBlocks uint8
	SReservedGdtBlocks uint16
	SJournalUUID [16]byte
	SJournalInum uint32
	SJournalDev uint32
	SLastOrphan uint32
	SHashSeed [4]uint32
	SDefHashVersion byte
	SJnlBackupType byte
	SDefaultMountOpts uint32
	SFirstMetaBg uint32
	SMkfsTime uint32
	SJnlBlocks [17]uint32
	SBlocksCountHi uint32
	SRBlocksCountHi uint32
	SFreeBlocksCountHi uint32
	SMinExtraIsize uint16
	SWantExtraIsize uint16
	SFlags uint32
	SRaidStride uint16
	SMmpInterval uint16
	SMmpBlock uint64
	SRaidStripeWidth uint32
	SLogGroupsPerFlex byte
	SChecksumType byte
	SReservedPad uint16
	SKbytesWritten uint64
	SSnapshotInum uint32
	SSnapshotId uint32
	SSnapshotRBlocksCount uint64
	SSnapshotList uint32
	SErrorCount uint32
	SFirstErrorTime uint32
	SFirstErrorIno uint32
	SFirstErrorBlock uint64
	SFirstErrorFunc [32]byte
	SFirstErrorLine uint32
	SLastErrorTime uint32
	SLastErrorIno uint32
	SLastErrorLine uint32
	SLastErrorBlock uint64
	SLastErrorFunc [32]byte
	SMountOpts [64]byte
	SUsrQuotaInum uint32
	SGrpQuotaInum uint32
	SOverheadBlocks uint32
	SBackupBgs [2]uint32
	SReserved [106]uint32
	SChecksum uint32
}
